<div>
    <p>
        <label>系统 ID</label>
    </p>
    <p>
        <label>称呼</label>
    </p>
    <p>
        <label>姓名</label>
    </p>
    <p>
        <label>电话</label>
    </p>
    <p>
        <label>Email</label>
    </p>
    <p>
        <label>年龄</label>
    </p>
    <p>
        <label>地址</label>
    </p>
    <p>
        <label>加入时间</label>
    </p>
    <p>
        <label>退出时间</label>
    </p>
    <p>
        <label>有（无）效</label>
    </p>
    <p>
        <label>客户类型</label>
    </p>
</div>
